name: Build library

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # OS additions
      - name: Add to OS
        run: |
           sudo apt-get install memcached
           
      # Checkout our code 
      - name: Checkout code
        uses: actions/checkout@v7

      # Setup NodeJS environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v7
        with:
          node-version: 22
          cache: 'npm'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
            php-version: 8.2
            extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, imagick, memcache
            coverage: xdebug

      # Validate the Composer files
      - name: Validate composer.json and composer.lock
        run: composer validate

      # Fetch the vendor folder from the cache, keyed off the composer.lock file 
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v6
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      # Run composer install if the vendor folder wasn't cached (based on the current composer.lock file) 
      - name: Install Composer dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress

      # install NPM dependencies
      - name: Install NPM dependencies
        run: npm install

      # build the app
      - name: Build
        run: |
          npm run build
